name: Web App test and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dotnet-steps:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore AvansMealDeal/AvansMealDeal.sln

      - name: Build with dotnet
        run: dotnet build AvansMealDeal/AvansMealDeal.sln --configuration Release

      - name: Unit tests
        run: dotnet test AvansMealDeal/AvansMealDeal.Tests/AvansMealDeal.Tests.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish AvansMealDeal/AvansMealDeal.UserInterface.WebApp/AvansMealDeal.UserInterface.WebApp.csproj --configuration Release -o "${{github.workspace}}/webapp-publish"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: webapp-publish
          path: ${{github.workspace}}/webapp-publish

      - name: Install EF migrations tool
        run: dotnet tool install --global dotnet-ef
      
      - name: Make EF migrations tool accessible
        run: echo "${{ github.workspace }}/.dotnet/tools" >> $GITHUB_PATH
      
      - name: Deploy EF migrations application database
        run: dotnet ef --project AvansMealDeal/AvansMealDeal.Infrastructure.Application.SQLServer/AvansMealDeal.Infrastructure.Application.SQLServer.csproj --startup-project AvansMealDeal/AvansMealDeal.UserInterface.WebApp/AvansMealDeal.UserInterface.WebApp.csproj database update --context DbContextApplicationSqlServer

      - name: Deploy EF migrations identity database
        run: dotnet ef --project AvansMealDeal/AvansMealDeal.Infrastructure.Identity.SQLServer/AvansMealDeal.Infrastructure.Identity.SQLServer.csproj --startup-project AvansMealDeal/AvansMealDeal.UserInterface.WebApp/AvansMealDeal.UserInterface.WebApp.csproj database update --context DbContextIdentitySqlServer

  azure-steps:
    runs-on: windows-latest
    needs: dotnet-steps
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp-publish
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_58E035AF49DB4EE0A1A94BA1ED13FC82 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5DA1BA0A069C4B3AB68D3CCC2236E2BD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CAAC00DEFFD3469584D211669871C2F8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'avansmealdeal-webapp'
          slot-name: 'Production'
          package: .
          