name: Web Service test and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dotnet-steps:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore AvansMealDeal/AvansMealDeal.sln

      - name: Build with dotnet
        run: dotnet build AvansMealDeal/AvansMealDeal.sln --configuration Release

      - name: Unit tests
        run: dotnet test AvansMealDeal/AvansMealDeal.Tests/AvansMealDeal.Tests.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish AvansMealDeal/AvansMealDeal.UserInterface.WebService/AvansMealDeal.UserInterface.WebService.csproj --configuration Release -o "${{github.workspace}}/webservice-publish"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: webservice-publish
          path: ${{github.workspace}}/webservice-publish

      - name: Install EF migrations tool
        run: dotnet tool install --global dotnet-ef
      
      - name: Make EF migrations tool accessible
        run: echo "${{ github.workspace }}/.dotnet/tools" >> $GITHUB_PATH
      
      - name: Deploy EF migrations application database
        run: dotnet ef --project AvansMealDeal/AvansMealDeal.Infrastructure.Application.SQLServer/AvansMealDeal.Infrastructure.Application.SQLServer.csproj database update --context DbContextApplicationSqlServer --connection "$DATABASES_APPLICATION"

      - name: Deploy EF migrations identity database
        run: dotnet ef --project AvansMealDeal/AvansMealDeal.Infrastructure.Identity.SQLServer/AvansMealDeal.Infrastructure.Identity.SQLServer.csproj database update --context DbContextIdentitySqlServer --connection "$DATABASES_IDENTITY"

  azure-steps:
    runs-on: windows-latest
    needs: dotnet-steps
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webservice-publish
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1B62744FB8C14096821C79DB31200966 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_571A095842764B348075294222B85601 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_08770DD2C0194B088713451C582DAB14 }}

      - name: Deploy to Azure Web Service
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'avansmealdeal-webservice'
          slot-name: 'Production'
          package: .
          